background = "#113851"
foreground = "#D8D7CD"

color00    = "#13415E" # black
color01    = "#D7595F" # red
color02    = "#B5BD68" # green
color03    = "#F2BF40" # yellow
color04    = "#81A2BE" # blue
color05    = "#B294BB" # magenta
color06    = "#47B0AB" # cyan
color07    = "#D8D7CD" # grey
color08    = "#A99688" # dark grey
color09    = "#D7595F" # bright red
color10    = "#B5BD68" # bright green
color11    = "#F2BF40" # bright yellow
color12    = "#81A2BE" # bright blue
color13    = "#B294BB" # bright magenta
color14    = "#47B0AB" # bright cyan
color15    = "#ECEBE6" # white

color208   = "#E58C4F" # orange
