background = "#113851"
foreground = "#D8D7CD"
color01    = "#D7595F" # red
color02    = "#B5BD68" # green
color03    = "#F2BF40" # yellow
color04    = "#81A2BE" # blue
color05    = "#B294BB" # magenta
color06    = "#47B0AB" # cyan
