# Catppuccin Mocha
background = "#181825"
foreground = "#cdd6f4"
color01    = "#f38ba8" # red
color02    = "#a6e3a1" # green
color03    = "#f9e2af" # yellow
color04    = "#89b4fa" # blue
color05    = "#cba6f7" # magenta
color06    = "#94e2d5" # cyan
