# Cobalt2 (Wes Bos)
# Source: https://github.com/wesbos/Cobalt2-iterm
background = "#132738"
foreground = "#ffffff"
cursor = "#ffffff"
color01 = "#ff0000"  # red
color02 = "#37de21"  # green
color03 = "#f4d300"  # yellow
color04 = "#14c2d2"  # blue
color05 = "#ff5dff"  # magenta
color06 = "#bbbb00"  # cyan
