background = "#282828"
foreground = "#A9B7C6"
color01    = "#BC3F3C" # red
color02    = "#A5C261" # green
color03    = "#FFC66D" # yellow
color04    = "#6897BB" # blue
color05    = "#9876AA" # magenta
color06    = "#89C0BE" # cyan
