background = "#282828"
foreground = "#A9B7C6"

color00    = "#3C3F41" # black
color01    = "#BC3F3C" # red
color02    = "#A5C261" # green
color03    = "#FFC66D" # yellow
color04    = "#6897BB" # blue
color05    = "#9876AA" # magenta
color06    = "#89C0BE" # cyan
color07    = "#BABABA" # grey
color08    = "#808080" # dark grey
color09    = "#BC3F3C" # bright red
color10    = "#A5C261" # bright green
color11    = "#FFC66D" # birght yellow
color12    = "#6897BB" # bright blue
color13    = "#9876AA" # bright magenta
color14    = "#89C0BE" # bright cyan
color15    = "#F4F4FA" # white

color208   = "#CC7832" # orange
