name = "everforest"

[dark]
slug = "everforest-dark"
background = "#2d353b"
foreground = "#d3c6aa"
color01 = "#e67e80"
color02 = "#a7c080"
color03 = "#dbbc7f"
color04 = "#7fbbb3"
color05 = "#d699b6"
color06 = "#83c092"

[light]
slug = "everforest-light"
background = "#fdf6e3"
foreground = "#5c6a72"
color01 = "#f85552"
color02 = "#8da101"
color03 = "#dfa000"
color04 = "#3a94c5"
color05 = "#df69ba"
color06 = "#35a77c"
