name = "flexoki"

[dark]
slug = "flexoki-dark"
background = "#100f0f"
foreground = "#cecdc3"
color01 = "#af3029"
color02 = "#66800b"
color03 = "#ad8301"
color04 = "#205ea6"
color05 = "#a02f6f"
color06 = "#24837b"

[light]
slug = "flexoki-light"
background = "#fffcf0"
foreground = "#100f0f"
color01 = "#af3029"
color02 = "#66800b"
color03 = "#ad8301"
color04 = "#205ea6"
color05 = "#a02f6f"
color06 = "#24837b"
