background = "#101216"
foreground = "#8B949E"
color01    = "#F78166" # red
color02    = "#56D364" # green
color03    = "#E3B341" # yellow
color04    = "#6CA4F8" # blue
color05    = "#DB61A2" # magenta
color06    = "#2B7489" # cyan
