background = "#101216"
foreground = "#8B949E"

color00    = "#1A1D23" # black
color01    = "#F78166" # red
color02    = "#56D364" # green
color03    = "#E3B341" # yellow
color04    = "#6CA4F8" # blue
color05    = "#DB61A2" # magenta
color06    = "#2B7489" # cyan
color07    = "#8B949E" # grey
color08    = "#4D4D4D" # dark grey
color09    = "#F78166" # bright red
color10    = "#56D364" # bright green
color11    = "#E3B341" # birght yellow
color12    = "#6CA4F8" # bright blue
color13    = "#DB61A2" # bright magenta
color14    = "#2B7489" # bright cyan
color15    = "#C5C9CF" # white

color208   = "#ED9A54" # orange
