background = "#ffffff"
foreground = "#3e3e3e"

color00    = "#e2e2e2" # black
color01    = "#970b16" # red
color02    = "#07962a" # green
color03    = "#dfb71c" # yellow
color04    = "#003e8a" # blue
color05    = "#e94691" # magenta
color06    = "#89d1ec" # cyan
color07    = "#3e3e3e" # grey
color08    = "#666666" # dark grey
color09    = "#970b16" # bright red
color10    = "#07962a" # bright green
color11    = "#dfb71c" # bright yellow
color12    = "#003e8a" # bright blue
color13    = "#e94691" # bright magenta
color14    = "#89d1ec" # bright cyan
color15    = "#232323" # white

color208   = "#bb6119" # orange
