background = "#081D08"
foreground = "#4AA23C"
color01    = "#2F6C1C" # red
color02    = "#50AD32" # green
color03    = "#58BD38" # yellow
color04    = "#46992C" # blue
color05    = "#317029" # magenta
color06    = "#50AD32" # cyan
