background = "#101010"
foreground = "#B9B9B9"
color01    = "#7C7C7C" # red
color02    = "#8E8E8E" # green
color03    = "#A0A0A0" # yellow
color04    = "#686868" # blue
color05    = "#747474" # magenta
color06    = "#868686" # cyan
