background = "#282828"
foreground = "#D5C4A1"
color01    = "#FB4934" # red
color02    = "#B8BB26" # green
color03    = "#FABD2F" # yellow
color04    = "#83A598" # blue
color05    = "#D3869B" # magenta
color06    = "#8EC07C" # cyan
