background = "#282828"
foreground = "#d5c4a1"

color00    = "#282828" # black
color01    = "#fb4934" # red
color02    = "#b8bb26" # green
color03    = "#fabd2f" # yellow
color04    = "#83a598" # blue
color05    = "#d3869b" # magenta
color06    = "#8ec07c" # cyan
color07    = "#d5c4a1" # grey
color08    = "#665c54" # dark grey
color09    = "#fb4934" # bright red
color10    = "#b8bb26" # bright green
color11    = "#fabd2f" # birght yellow
color12    = "#83a598" # bright blue
color13    = "#d3869b" # bright magenta
color14    = "#8ec07c" # bright cyan
color15    = "#fbf1c7" # white

color208   = "#fe8019" # orange
color247   = "#3c3836" # black +5
