background = "#282828"
foreground = "#D5C4A1"

color00    = "#353535" # black
color01    = "#FB4934" # red
color02    = "#B8BB26" # green
color03    = "#FABD2F" # yellow
color04    = "#83A598" # blue
color05    = "#D3869B" # magenta
color06    = "#8EC07C" # cyan
color07    = "#D5C4A1" # grey
color08    = "#7F7664" # dark grey
color09    = "#FB4934" # bright red
color10    = "#B8BB26" # bright green
color11    = "#FABD2F" # bright yellow
color12    = "#83A598" # bright blue
color13    = "#D3869B" # bright magenta
color14    = "#8EC07C" # bright cyan
color15    = "#FBF1C7" # white

color208   = "#FE8019" # orange
