background = "#FBF1C7"
foreground = "#504945"
color01    = "#9D0006" # red
color02    = "#79740E" # green
color03    = "#B57614" # yellow
color04    = "#076678" # blue
color05    = "#8F3F71" # magenta
color06    = "#427B58" # cyan
