background = "#101421"
foreground = "#FFFBF6"
color01    = "#EB4129" # red
color02    = "#ABE047" # green
color03    = "#F6C744" # yellow
color04    = "#47A0F3" # blue
color05    = "#7B5CB0" # magenta
color06    = "#64DBED" # cyan
