background = "#101421"
foreground = "#FFFBF6"

color00    = "#191F34" # black
color01    = "#EB4129" # red
color02    = "#ABE047" # green
color03    = "#F6C744" # yellow
color04    = "#47A0F3" # blue
color05    = "#7B5CB0" # magenta
color06    = "#64DBED" # cyan
color07    = "#E5E9F0" # grey
color08    = "#565656" # dark grey
color09    = "#EC5357" # bright red
color10    = "#C0E17D" # bright green
color11    = "#F9DA6A" # birght yellow
color12    = "#49A4F8" # bright blue
color13    = "#A47DE9" # bright magenta
color14    = "#99FAF2" # bright cyan
color15    = "#FFFFFF" # white

color208   = "#F18437" # orange
