background = "#2B2B2B"
foreground = "#BBBBBB"
color01    = "#DB5451" # red
color02    = "#548C26" # green
color03    = "#A89022" # yellow
color04    = "#3A91CF" # blue
color05    = "#A575BA" # magenta
color06    = "#009191" # cyan
