# Material Theme Palenight
background = "#292D3E"
foreground = "#A6ACCD"
color01    = "#F07178"
color02    = "#C3E88D"
color03    = "#FFCB6B"
color04    = "#82AAFF"
color05    = "#C792EA"
color06    = "#89DDFF"
