background = "#121212"
foreground = "#BBBBBB"
color01    = "#FA2573" # red
color02    = "#98E123" # green
color03    = "#DFD460" # yellow
color04    = "#1080D0" # blue
color05    = "#8700FF" # magenta
color06    = "#43A8D0" # cyan
