# Monokai Pro Sun
background = "#fff9e4"
foreground = "#403e41"
color01    = "#ff6188"
color02    = "#a9dc76"
color03    = "#ffd866"
color04    = "#78dce8"
color05    = "#ab9df2"
color06    = "#78dce8"
