name = "nightfox"

[dark]
slug = "nightfox"
background = "#192330"
foreground = "#cdcecf"
color01 = "#c94f6d"
color02 = "#81b29a"
color03 = "#dbc074"
color04 = "#719cd6"
color05 = "#9d79d6"
color06 = "#63cdcf"

[light]
slug = "dayfox"
background = "#f6f2ee"
foreground = "#3d2b5a"
color01 = "#a5222f"
color02 = "#396847"
color03 = "#ac5402"
color04 = "#2848a9"
color05 = "#6e33ce"
color06 = "#287980"
