background = "#2E3440"
foreground = "#D8DEE9"

color00    = "#3B4252" # black
color01    = "#BF616A" # red
color02    = "#A3BE8C" # green
color03    = "#EBCB8B" # yellow
color04    = "#81A1C1" # blue
color05    = "#B48EAD" # magenta
color06    = "#88C0D0" # cyan
color07    = "#757A85" # grey
color08    = "#757A85" # dark grey
color09    = "#BF616A" # bright red
color10    = "#A3BE8C" # bright green
color11    = "#EBCB8B" # bright yellow
color12    = "#81A1C1" # bright blue
color13    = "#B48EAD" # bright magenta
color14    = "#88C0D0" # bright cyan
color15    = "#ECEFF4" # white

color208   = "#D08770" # orange
