background = "#2e3440"
foreground = "#d8dee9"

color00    = "#2e3440" # black
color01    = "#bf616a" # red
color02    = "#a3be8c" # green
color03    = "#ebcb8b" # yellow
color04    = "#81a1c1" # blue
color05    = "#b48ead" # magenta
color06    = "#88c0d0" # cyan
color07    = "#e5e9f0" # grey
color08    = "#4c566a" # dark grey
color09    = "#bf616a" # bright red
color10    = "#a3be8c" # bright green
color11    = "#ebcb8b" # birght yellow
color12    = "#81a1c1" # bright blue
color13    = "#b48ead" # bright magenta
color14    = "#88c0d0" # bright cyan
color15    = "#eceff4" # white

color208   = "#d08770" # orange
color247   = "#3b4252" # black +5
