background = "#282C34"
foreground = "#ABB2BF"

color00    = "#353B45" # black
color01    = "#E06C75" # red
color02    = "#98C379" # green
color03    = "#E5C07B" # yellow
color04    = "#61AFEF" # blue
color05    = "#C678DD" # magenta
color06    = "#56B6C2" # cyan
color07    = "#ABB2BF" # grey
color08    = "#545862" # dark grey
color09    = "#E06C75" # bright red
color10    = "#98C379" # bright green
color11    = "#E5C07B" # birght yellow
color12    = "#61AFEF" # bright blue
color13    = "#C678DD" # bright magenta
color14    = "#56B6C2" # bright cyan
color15    = "#C8CCD4" # white

color208   = "#D19A66" # orange
