background = "#fafafa"
foreground = "#383a42"

color00    = "#fafafa" # black
color01    = "#ca1243" # red
color02    = "#50a14f" # green
color03    = "#c18401" # yellow
color04    = "#4078f2" # blue
color05    = "#a626a4" # magenta
color06    = "#0184bc" # cyan
color07    = "#383a42" # grey
color08    = "#a0a1a7" # dark grey
color09    = "#ca1243" # bright red
color10    = "#50a14f" # bright green
color11    = "#c18401" # birght yellow
color12    = "#4078f2" # bright blue
color13    = "#a626a4" # bright magenta
color14    = "#0184bc" # bright cyan
color15    = "#090a0b" # white

color208   = "#d75f00" # orange
color247   = "#f0f0f1" # black +5
