# Rose Pine Dawn (Light)
background = "#faf4ed"
foreground = "#575279"
# For light themes: black is darker than background
color01    = "#b4637a" # red
color02    = "#286983" # green
color03    = "#ea9d34" # yellow
color04    = "#56949f" # blue
color05    = "#907aa9" # magenta
color06    = "#d7827e" # cyan
