background = "#002B36"
foreground = "#93A1A1"

color00    = "#073642" # black
color01    = "#DC322F" # red
color02    = "#859900" # green
color03    = "#B58900" # yellow
color04    = "#268BD2" # blue
color05    = "#6C71C4" # magenta
color06    = "#2AA198" # cyan
color07    = "#93A1A1" # grey
color08    = "#657B83" # dark grey
color09    = "#DC322F" # bright red
color10    = "#859900" # bright green
color11    = "#B58900" # bright yellow
color12    = "#268BD2" # bright blue
color13    = "#6C71C4" # bright magenta
color14    = "#2AA198" # bright cyan
color15    = "#FDF6E3" # white

color208   = "#C95E17" # orange
