background = "#000000"
foreground = "#00FF00"
color01    = "#CC0000" # red
color02    = "#73D216" # green
color03    = "#EDD400" # yellow
color04    = "#3465A4" # blue
color05    = "#75507B" # magenta
color06    = "#06989A" # cyan
