background = "#000000"
foreground = "#00FF00"

color00    = "#3B4245" # black
color01    = "#CC0000" # red
color02    = "#73D216" # green
color03    = "#EDD400" # yellow
color04    = "#3465A4" # blue
color05    = "#75507B" # magenta
color06    = "#06989A" # cyan
color07    = "#D3D7CF" # grey
color08    = "#2E3436" # dark grey
color09    = "#EF2929" # bright red
color10    = "#8AE234" # bright green
color11    = "#FCE94F" # birght yellow
color12    = "#729FCF" # bright blue
color13    = "#AD7FA8" # bright magenta
color14    = "#34E2E2" # bright cyan
color15    = "#EEEEEC" # white

color208   = "#DD6A00" # orange
