background = "#000000"
foreground = "#00ff00"

color00    = "#2e3436" # black
color01    = "#cc0000" # red
color02    = "#73d216" # green
color03    = "#edd400" # yellow
color04    = "#3465a4" # blue
color05    = "#75507b" # magenta
color06    = "#06989a" # cyan
color07    = "#d3d7cf" # grey
color08    = "#2e3436" # dark grey
color09    = "#ef2929" # bright red
color10    = "#8ae234" # bright green
color11    = "#fce94f" # birght yellow
color12    = "#729fcf" # bright blue
color13    = "#ad7fa8" # bright magenta
color14    = "#34e2e2" # bright cyan
color15    = "#eeeeec" # white

color208   = "#DD6A00" # orange
color247   = "#3b4245" # black +5
