background = "#282828"
foreground = "#EEEEEE"
color01    = "#F43753" # red
color02    = "#C9D05C" # green
color03    = "#FFC24B" # yellow
color04    = "#B3DEEF" # blue
color05    = "#D3B987" # magenta
color06    = "#73CEF4" # cyan
