background = "#282828"
foreground = "#EEEEEE"

color00    = "#363636" # black
color01    = "#F43753" # red
color02    = "#C9D05C" # green
color03    = "#FFC24B" # yellow
color04    = "#B3DEEF" # blue
color05    = "#D3B987" # magenta
color06    = "#73CEF4" # cyan
color07    = "#EEEEEE" # grey
color08    = "#4C4C4C" # dark grey
color09    = "#F43753" # bright red
color10    = "#C9D05C" # bright green
color11    = "#FFC24B" # bright yellow
color12    = "#B3DEEF" # bright blue
color13    = "#D3B987" # bright magenta
color14    = "#73CEF4" # bright cyan
color15    = "#FEFFFF" # white

color208   = "#FA7D4F" # orange
