background = "#24283B"
foreground = "#A9B1D6"
color01    = "#F7768E" # red
color02    = "#9ECE6A" # green
color03    = "#E0AF68" # yellow
color04    = "#7AA2F7" # blue
color05    = "#AD8EE6" # magenta
color06    = "#449DAB" # cyan
