background = "#1D1F21"
foreground = "#C5C8C6"
color01    = "#CC6666" # red
color02    = "#B5BD68" # green
color03    = "#F0C674" # yellow
color04    = "#81A2BE" # blue
color05    = "#B294BB" # magenta
color06    = "#8ABEB7" # cyan
