background = "#0a0b0c"
foreground = "#696b69"

color00    = "#0a0b0c" # black
color01    = "#6d3333" # red
color02    = "#606434" # green
color03    = "#81693b" # yellow
color04    = "#435565" # blue
color05    = "#5e4d63" # magenta
color06    = "#486561" # cyan
color07    = "#696b69" # grey
color08    = "#4e4f4e" # dark grey
color09    = "#6d3333" # bright red
color10    = "#606434" # bright green
color11    = "#81693b" # birght yellow
color12    = "#435565" # bright blue
color13    = "#5e4d63" # bright magenta
color14    = "#486561" # bright cyan
color15    = "#898989" # white

color208   = "#774d2f" # orange
color247   = "#101214" # black +5
