background = "#0A0B0C"
foreground = "#696B69"
color01    = "#6D3333" # red
color02    = "#606434" # green
color03    = "#81693B" # yellow
color04    = "#435565" # blue
color05    = "#5E4D63" # magenta
color06    = "#486561" # cyan
