background = "#1E1E1E"
foreground = "#CCCCCC"

color00    = "#2B2B2B" # black
color01    = "#CD3131" # red
color02    = "#0DBC79" # green
color03    = "#E5E510" # yellow
color04    = "#2472C8" # blue
color05    = "#BC3FBC" # magenta
color06    = "#11A8CD" # cyan
color07    = "#E5E5E5" # grey
color08    = "#666666" # dark grey
color09    = "#F14C4C" # bright red
color10    = "#23D18B" # bright green
color11    = "#F5F543" # birght yellow
color12    = "#3B8EEA" # bright blue
color13    = "#D670D6" # bright magenta
color14    = "#29B8DB" # bright cyan
color15    = "#E5E5E5" # white

color208   = "#D98B21" # orange
