background = "#1E1E1E"
foreground = "#CCCCCC"
color01    = "#CD3131" # red
color02    = "#0DBC79" # green
color03    = "#E5E510" # yellow
color04    = "#2472C8" # blue
color05    = "#BC3FBC" # magenta
color06    = "#11A8CD" # cyan
