#!/usr/bin/env bash
# Theme: ayu-dark
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="04/06/0B"
color01="ea/6c/73"
color02="91/b3/62"
color03="f9/af/4f"
color04="53/bd/fa"
color05="fa/e9/94"
color06="90/e1/c6"
color07="b3/b1/ad"
color08="44/45/47"
color09="FF/A1/A3"
color10="B5/DA/83"
color11="FF/DE/BA"
color12="AF/DF/FF"
color13="F8/E6/8C"
color14="A3/F9/DC"
color15="CC/CA/C6"
color208="F2/8F/65"
color_background="0b/0e/14"
color_foreground="b3/b1/ad"

export WALH_THEME="ayu-dark"
export WALH_MODE="dark"
export WALH_BG="#0b0e14"
export WALH_FG="#b3b1ad"
export COLORFGBG="15;0"

_walh_bg_hex="0b0e14"
_walh_fg_hex="b3b1ad"
_walh_surface_hex="04060B"
_walh_dim_hex="444547"
_walh_b03_hex="f9af4f"
_walh_b15_hex="CCCAC6"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
