#!/usr/bin/env bash
# Theme: ayu-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="EB/EB/EB"
color01="f0/71/71"
color02="6c/ba/78"
color03="fa/8d/3e"
color04="36/a3/d9"
color05="a3/7a/cc"
color06="4c/bf/99"
color07="57/5f/66"
color08="B8/BC/C0"
color09="DE/4D/52"
color10="46/A3/58"
color11="E2/71/00"
color12="00/8A/C0"
color13="8D/5E/BA"
color14="00/A8/7F"
color15="3C/44/4A"
color208="F5/7F/5C"
color_background="fa/fa/fa"
color_foreground="57/5f/66"

export WALH_THEME="ayu-light"
export WALH_MODE="light"
export WALH_BG="#fafafa"
export WALH_FG="#575f66"
export COLORFGBG="0;15"

_walh_bg_hex="fafafa"
_walh_fg_hex="575f66"
_walh_surface_hex="EBEBEB"
_walh_dim_hex="B8BCC0"
_walh_b03_hex="fa8d3e"
_walh_b15_hex="3C444A"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
