#!/usr/bin/env bash
# Theme: catppuccin-latte
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="E0/E2/E6"
color01="d2/0f/39"
color02="40/a0/2b"
color03="df/8e/1d"
color04="1e/66/f5"
color05="88/39/ef"
color06="17/92/99"
color07="4c/4f/69"
color08="AD/B0/C1"
color09="AC/00/2B"
color10="23/87/00"
color11="C1/77/00"
color12="00/4C/D8"
color13="73/00/D6"
color14="00/78/7F"
color15="32/34/4D"
color208="DB/5E/31"
color_background="ef/f1/f5"
color_foreground="4c/4f/69"

export WALH_THEME="catppuccin-latte"
export WALH_MODE="light"
export WALH_BG="#eff1f5"
export WALH_FG="#4c4f69"
export COLORFGBG="0;15"

_walh_bg_hex="eff1f5"
_walh_fg_hex="4c4f69"
_walh_surface_hex="E0E2E6"
_walh_dim_hex="ADB0C1"
_walh_b03_hex="df8e1d"
_walh_b15_hex="32344D"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
