#!/usr/bin/env bash
# Theme: catppuccin-mocha
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="0F/0F/1B"
color01="f3/8b/a8"
color02="a6/e3/a1"
color03="f9/e2/af"
color04="89/b4/fa"
color05="cb/a6/f7"
color06="94/e2/d5"
color07="cd/d6/f4"
color08="55/59/6D"
color09="FF/C3/D2"
color10="B8/F9/B2"
color11="FA/E2/AC"
color12="C5/DB/FF"
color13="E9/D8/FF"
color14="A4/F7/E9"
color15="ED/F1/FF"
color208="F8/B7/AC"
color_background="18/18/25"
color_foreground="cd/d6/f4"

export WALH_THEME="catppuccin-mocha"
export WALH_MODE="dark"
export WALH_BG="#181825"
export WALH_FG="#cdd6f4"
export COLORFGBG="15;0"

_walh_bg_hex="181825"
_walh_fg_hex="cdd6f4"
_walh_surface_hex="0F0F1B"
_walh_dim_hex="55596D"
_walh_b03_hex="f9e2af"
_walh_b15_hex="EDF1FF"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
