#!/usr/bin/env bash
# Theme: catppuccin-mocha
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# Normal
color00="0F/0F/1B" # Black
color01="f3/8b/a8" # Red
color02="a6/e3/a1" # Green
color03="f9/e2/af" # Yellow
color04="89/b4/fa" # Blue
color05="cb/a6/f7" # Magenta
color06="94/e2/d5" # Cyan
color07="cd/d6/f4" # Grey

# Bright
color08="55/59/6D" # Dark Grey
color09="FF/C3/D2" # Red
color10="B8/F9/B2" # Green
color11="FA/E2/AC" # Yellow
color12="C5/DB/FF" # Blue
color13="E9/D8/FF" # Magenta
color14="A4/F7/E9" # Cyan
color15="ED/F1/FF" # White

# 256 color
color208="F8/B7/AC" # Orange

# Base
color_background="18/18/25" # Black
color_foreground="cd/d6/f4" # Grey

# Announce the active palette to programs launched from this shell
export WALH_THEME="catppuccin-mocha"
export WALH_MODE="dark"
export WALH_BG="#181825"
export WALH_FG="#cdd6f4"
# ncurses/rxvt convention: programs like mutt and rho read this to adopt
# the palette's mode without querying the terminal
export COLORFGBG="15;0"
if [ -z "$WALH_RESTORE" ]; then
  state_dir="${XDG_CACHE_HOME:-$HOME/.cache}/walh"
  mkdir -p "$state_dir"
  cat > "$state_dir/state.toml" <<STATEEOF
theme = "catppuccin-mocha"
mode = "dark"
background = "#181825"
foreground = "#cdd6f4"
surface = "#0F0F1B"
dim = "#55596D"
STATEEOF
fi

walh_buffer=""
if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ]; then
  walh_append() {
    local _c
    # shellcheck disable=SC2059
    printf -v _c "$@"
    walh_buffer="${walh_buffer}${_c}"
  }
else
  walh_append() {
    # shellcheck disable=SC2059
    walh_buffer="${walh_buffer}$(printf "$@")"
  }
fi

# shellcheck disable=SC1003
if [ -n "$TMUX" ]; then
  # Tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  put_template() { walh_append '\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\' "$@"; }
  put_template_var() { walh_append '\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\' "$@"; }
  put_template_custom() { walh_append '\033Ptmux;\033\033]%s%s\033\033\\\033\\' "$@"; }
elif [ "${TERM%%[-.]*}" = "screen" ]; then
  # GNU screen (screen, screen-256color, screen-256color-bce)
  put_template() { walh_append '\033P\033]4;%d;rgb:%s\007\033\\' "$@"; }
  put_template_var() { walh_append '\033P\033]%d;rgb:%s\007\033\\' "$@"; }
  put_template_custom() { walh_append '\033P\033]%s%s\007\033\\' "$@"; }
elif [ "${TERM%%-*}" = "linux" ]; then
  put_template() { [ "$1" -lt 16 ] && walh_append '\033]P%x%s' "$1" "$(echo "$2" | sed 's/\///g')"; }
  put_template_var() { true; }
  put_template_custom() { true; }
else
  put_template() { walh_append '\033]4;%d;rgb:%s\033\\' "$@"; }
  put_template_var() { walh_append '\033]%d;rgb:%s\033\\' "$@"; }
  put_template_custom() { walh_append '\033]%s%s\033\\' "$@"; }
fi

# 16 color space
put_template 0 "$color00"
put_template 1 "$color01"
put_template 2 "$color02"
put_template 3 "$color03"
put_template 4 "$color04"
put_template 5 "$color05"
put_template 6 "$color06"
put_template 7 "$color07"
put_template 8 "$color08"
put_template 9 "$color09"
put_template 10 "$color10"
put_template 11 "$color11"
put_template 12 "$color12"
put_template 13 "$color13"
put_template 14 "$color14"
put_template 15 "$color15"

# 256 color space
put_template 208 "$color208"

# foreground / background / cursor color
if [ -n "$ITERM_SESSION_ID" ]; then
  # iTerm2 proprietary escape codes
  put_template_custom Pg cdd6f4 # foreground
  put_template_custom Ph 181825 # background
  put_template_custom Pi EDF1FF # bold color
  put_template_custom Pj f9e2af # selection color
  put_template_custom Pk 181825 # selected text color
  put_template_custom Pl cdd6f4 # cursor
  put_template_custom Pm 181825 # cursor text
else
  put_template_var 10 "$color_foreground"
  if [ "$WALH_SHELL_SET_BACKGROUND" != false ]; then
    put_template_var 11 "$color_background"
    if [ "${TERM%%-*}" = "rxvt" ]; then
      put_template_var 708 "$color_background" # internal border (rxvt)
    fi
  fi
  put_template_custom 12 ";7" # cursor (reverse video)
fi

[ -n "$walh_buffer" ] && printf '%s' "$walh_buffer"

# clean up
for fn in walh_append put_template put_template_var put_template_custom; do
  unset -f "$fn" 2>/dev/null || true
done
for var in \
  walh_buffer \
  color00 color01 color02 color03 color04 color05 color06 color07 \
  color08 color09 color10 color11 color12 color13 color14 color15 \
  color208 color_foreground color_background state_dir; do
  unset "$var" 2>/dev/null || true
done
