#!/usr/bin/env bash
# Theme: cyan-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# Normal
color00="D6/F0/EF" # Black
color01="47/8F/8F" # Red
color02="2C/93/93" # Green
color03="23/6a/6a" # Yellow
color04="55/8D/8D" # Blue
color05="5A/88/88" # Magenta
color06="39/94/94" # Cyan
color07="AA/D9/D8" # Grey

# Bright
color08="8A/C8/C8" # Dark Grey
color09="47/8F/8F" # Red
color10="2C/93/93" # Green
color11="23/6a/6a" # Yellow
color12="55/8D/8D" # Blue
color13="5A/88/88" # Magenta
color14="39/94/94" # Cyan
color15="DD/F4/F2" # White

# 256 color
color208="46/9F/9F" # Orange

# Base
color_background="ea/fb/f9" # Black
color_foreground="6a/b8/b8" # Grey

# Announce the active palette to programs launched from this shell
export WALH_MODE=light
state_dir="${XDG_CACHE_HOME:-$HOME/.cache}/walh"
mkdir -p "$state_dir"
cat > "$state_dir/state.toml" <<STATEEOF
mode = "light"
background = "#eafbf9"
foreground = "#6ab8b8"
surface = "#D6F0EF"
dim = "#8AC8C8"
STATEEOF

if [ -n "$TMUX" ]; then
  # Tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  put_template() { printf '\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\' "$@"; }
  put_template_var() { printf '\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\' "$@"; }
  put_template_custom() { printf '\033Ptmux;\033\033]%s%s\033\033\\\033\\' "$@"; }
  # tmux parses default fg/bg (OSC 10/11) natively: sent unwrapped, tmux
  # tracks them and answers colour queries with the live theme instead of a
  # background it learned at tmux startup.
  put_template_var_native() { printf '\033]%d;rgb:%s\033\\' "$@"; }
elif [ "${TERM%%[-.]*}" = "screen" ]; then
  # GNU screen (screen, screen-256color, screen-256color-bce)
  put_template() { printf '\033P\033]4;%d;rgb:%s\007\033\\' "$@"; }
  put_template_var() { printf '\033P\033]%d;rgb:%s\007\033\\' "$@"; }
  put_template_custom() { printf '\033P\033]%s%s\007\033\\' "$@"; }
elif [ "${TERM%%-*}" = "linux" ]; then
  put_template() { [ "$1" -lt 16 ] && printf "\e]P%x%s" "$1" "$(echo "$2" | sed 's/\///g')"; }
  put_template_var() { true; }
  put_template_custom() { true; }
else
  put_template() { printf '\033]4;%d;rgb:%s\033\\' "$@"; }
  put_template_var() { printf '\033]%d;rgb:%s\033\\' "$@"; }
  put_template_custom() { printf '\033]%s%s\033\\' "$@"; }
fi

# 16 color space
put_template 0 "$color00"
put_template 1 "$color01"
put_template 2 "$color02"
put_template 3 "$color03"
put_template 4 "$color04"
put_template 5 "$color05"
put_template 6 "$color06"
put_template 7 "$color07"
put_template 8 "$color08"
put_template 9 "$color09"
put_template 10 "$color10"
put_template 11 "$color11"
put_template 12 "$color12"
put_template 13 "$color13"
put_template 14 "$color14"
put_template 15 "$color15"

# 256 color space
put_template 208 "$color208"

# foreground / background / cursor color
if [ -n "$ITERM_SESSION_ID" ]; then
  # iTerm2 proprietary escape codes
  put_template_custom Pg 6ab8b8 # foreground
  put_template_custom Ph eafbf9 # background
  put_template_custom Pi DDF4F2 # bold color
  put_template_custom Pj 236a6a # selection color
  put_template_custom Pk eafbf9 # selected text color
  put_template_custom Pl 6ab8b8 # cursor
  put_template_custom Pm eafbf9 # cursor text
else
  put_template_var_native 10 "$color_foreground"
  if [ "$WALH_SHELL_SET_BACKGROUND" != false ]; then
    put_template_var_native 11 "$color_background"
    if [ "${TERM%%-*}" = "rxvt" ]; then
      put_template_var 708 "$color_background" # internal border (rxvt)
    fi
  fi
  put_template_custom 12 ";7" # cursor (reverse video)
fi

# clean up
for fn in put_template put_template_var put_template_var_native put_template_custom; do
  unset -f "$fn" 2>/dev/null || true
done
for var in \
  color00 color01 color02 color03 color04 color05 color06 color07 \
  color08 color09 color10 color11 color12 color13 color14 color15 \
  color208 color_foreground color_background state_dir; do
  unset "$var" 2>/dev/null || true
done
