#!/usr/bin/env bash
# Theme: dayfox
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="E7/E3/DF"
color01="a5/22/2f"
color02="39/68/47"
color03="ac/54/02"
color04="28/48/a9"
color05="6e/33/ce"
color06="28/79/80"
color07="3d/2b/5a"
color08="AB/A0/BA"
color09="87/00/1B"
color10="19/53/2E"
color11="8B/42/00"
color12="10/29/9B"
color13="5A/00/B6"
color14="00/62/69"
color15="24/11/3E"
color208="A9/3E/22"
color_background="f6/f2/ee"
color_foreground="3d/2b/5a"

export WALH_THEME="dayfox"
export WALH_MODE="light"
export WALH_BG="#f6f2ee"
export WALH_FG="#3d2b5a"
export COLORFGBG="0;15"

_walh_bg_hex="f6f2ee"
_walh_fg_hex="3d2b5a"
_walh_surface_hex="E7E3DF"
_walh_dim_hex="ABA0BA"
_walh_b03_hex="ac5402"
_walh_b15_hex="24113E"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
