#!/usr/bin/env bash
# Theme: dracula-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="E9/E9/E3"
color01="ff/55/55"
color02="50/fa/7b"
color03="f1/fa/8c"
color04="bd/93/f9"
color05="ff/79/c6"
color06="8b/e9/fd"
color07="28/2a/36"
color08="A1/A3/A8"
color09="EE/14/2F"
color10="00/E0/5C"
color11="D7/E0/5C"
color12="A7/75/E9"
color13="EC/52/B0"
color14="5F/D1/E8"
color15="11/12/1D"
color208="FF/AF/73"
color_background="f8/f8/f2"
color_foreground="28/2a/36"

export WALH_THEME="dracula-light"
export WALH_MODE="light"
export WALH_BG="#f8f8f2"
export WALH_FG="#282a36"
export COLORFGBG="0;15"

_walh_bg_hex="f8f8f2"
_walh_fg_hex="282a36"
_walh_surface_hex="E9E9E3"
_walh_dim_hex="A1A3A8"
_walh_b03_hex="f1fa8c"
_walh_b15_hex="11121D"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
