#!/usr/bin/env bash
# Theme: dracula-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# Normal
color00="E9/E9/E3" # Black
color01="ff/55/55" # Red
color02="50/fa/7b" # Green
color03="f1/fa/8c" # Yellow
color04="bd/93/f9" # Blue
color05="ff/79/c6" # Magenta
color06="8b/e9/fd" # Cyan
color07="28/2a/36" # Grey

# Bright
color08="A1/A3/A8" # Dark Grey
color09="EE/14/2F" # Red
color10="00/E0/5C" # Green
color11="D7/E0/5C" # Yellow
color12="A7/75/E9" # Blue
color13="EC/52/B0" # Magenta
color14="5F/D1/E8" # Cyan
color15="11/12/1D" # White

# 256 color
color208="FF/AF/73" # Orange

# Base
color_background="f8/f8/f2" # Black
color_foreground="28/2a/36" # Grey

# Announce the active palette to programs launched from this shell
export WALH_THEME="dracula-light"
export WALH_MODE="light"
export WALH_BG="#f8f8f2"
export WALH_FG="#282a36"
# ncurses/rxvt convention: programs like mutt and rho read this to adopt
# the palette's mode without querying the terminal
export COLORFGBG="0;15"
if [ -z "$WALH_RESTORE" ]; then
  state_dir="${XDG_CACHE_HOME:-$HOME/.cache}/walh"
  mkdir -p "$state_dir"
  cat > "$state_dir/state.toml" <<STATEEOF
theme = "dracula-light"
mode = "light"
background = "#f8f8f2"
foreground = "#282a36"
surface = "#E9E9E3"
dim = "#A1A3A8"
STATEEOF
fi

walh_buffer=""
if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ]; then
  walh_append() {
    local _c
    # shellcheck disable=SC2059
    printf -v _c "$@"
    walh_buffer="${walh_buffer}${_c}"
  }
else
  walh_append() {
    # shellcheck disable=SC2059
    walh_buffer="${walh_buffer}$(printf "$@")"
  }
fi

# shellcheck disable=SC1003
if [ -n "$TMUX" ]; then
  # Tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  put_template() { walh_append '\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\' "$@"; }
  put_template_var() { walh_append '\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\' "$@"; }
  put_template_custom() { walh_append '\033Ptmux;\033\033]%s%s\033\033\\\033\\' "$@"; }
elif [ "${TERM%%[-.]*}" = "screen" ]; then
  # GNU screen (screen, screen-256color, screen-256color-bce)
  put_template() { walh_append '\033P\033]4;%d;rgb:%s\007\033\\' "$@"; }
  put_template_var() { walh_append '\033P\033]%d;rgb:%s\007\033\\' "$@"; }
  put_template_custom() { walh_append '\033P\033]%s%s\007\033\\' "$@"; }
elif [ "${TERM%%-*}" = "linux" ]; then
  put_template() { [ "$1" -lt 16 ] && walh_append '\033]P%x%s' "$1" "$(echo "$2" | sed 's/\///g')"; }
  put_template_var() { true; }
  put_template_custom() { true; }
else
  put_template() { walh_append '\033]4;%d;rgb:%s\033\\' "$@"; }
  put_template_var() { walh_append '\033]%d;rgb:%s\033\\' "$@"; }
  put_template_custom() { walh_append '\033]%s%s\033\\' "$@"; }
fi

# 16 color space
put_template 0 "$color00"
put_template 1 "$color01"
put_template 2 "$color02"
put_template 3 "$color03"
put_template 4 "$color04"
put_template 5 "$color05"
put_template 6 "$color06"
put_template 7 "$color07"
put_template 8 "$color08"
put_template 9 "$color09"
put_template 10 "$color10"
put_template 11 "$color11"
put_template 12 "$color12"
put_template 13 "$color13"
put_template 14 "$color14"
put_template 15 "$color15"

# 256 color space
put_template 208 "$color208"

# foreground / background / cursor color
if [ -n "$ITERM_SESSION_ID" ]; then
  # iTerm2 proprietary escape codes
  put_template_custom Pg 282a36 # foreground
  put_template_custom Ph f8f8f2 # background
  put_template_custom Pi 11121D # bold color
  put_template_custom Pj f1fa8c # selection color
  put_template_custom Pk f8f8f2 # selected text color
  put_template_custom Pl 282a36 # cursor
  put_template_custom Pm f8f8f2 # cursor text
else
  put_template_var 10 "$color_foreground"
  if [ "$WALH_SHELL_SET_BACKGROUND" != false ]; then
    put_template_var 11 "$color_background"
    if [ "${TERM%%-*}" = "rxvt" ]; then
      put_template_var 708 "$color_background" # internal border (rxvt)
    fi
  fi
  put_template_custom 12 ";7" # cursor (reverse video)
fi

[ -n "$walh_buffer" ] && printf '%s' "$walh_buffer"

# clean up
for fn in walh_append put_template put_template_var put_template_custom; do
  unset -f "$fn" 2>/dev/null || true
done
for var in \
  walh_buffer \
  color00 color01 color02 color03 color04 color05 color06 color07 \
  color08 color09 color10 color11 color12 color13 color14 color15 \
  color208 color_foreground color_background state_dir; do
  unset "$var" 2>/dev/null || true
done
