#!/usr/bin/env bash
# Theme: dracula
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="1E/20/2C"
color01="ff/55/55"
color02="50/fa/7b"
color03="f1/fa/8c"
color04="bd/93/f9"
color05="ff/79/c6"
color06="8b/e9/fd"
color07="f8/f8/f2"
color08="70/71/76"
color09="FF/A1/9A"
color10="9F/FF/AE"
color11="E6/EE/7A"
color12="DB/C6/FF"
color13="FF/C0/E0"
color14="B1/F1/FF"
color15="FC/FC/F6"
color208="FF/AF/73"
color_background="28/2a/36"
color_foreground="f8/f8/f2"

export WALH_THEME="dracula"
export WALH_MODE="dark"
export WALH_BG="#282a36"
export WALH_FG="#f8f8f2"
export COLORFGBG="15;0"

_walh_bg_hex="282a36"
_walh_fg_hex="f8f8f2"
_walh_surface_hex="1E202C"
_walh_dim_hex="707176"
_walh_b03_hex="f1fa8c"
_walh_b15_hex="FCFCF6"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
