#!/usr/bin/env bash
# Theme: everforest-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="EE/E7/D4"
color01="f8/55/52"
color02="8d/a1/01"
color03="df/a0/00"
color04="3a/94/c5"
color05="df/69/ba"
color06="35/a7/7c"
color07="5c/6a/72"
color08="BA/BF/BA"
color09="E6/1A/2C"
color10="76/87/00"
color11="C0/89/00"
color12="00/7C/AF"
color13="CC/43/A5"
color14="00/8E/64"
color15="41/4E/56"
color208="ED/7F/3C"
color_background="fd/f6/e3"
color_foreground="5c/6a/72"

export WALH_THEME="everforest-light"
export WALH_MODE="light"
export WALH_BG="#fdf6e3"
export WALH_FG="#5c6a72"
export COLORFGBG="0;15"

_walh_bg_hex="fdf6e3"
_walh_fg_hex="5c6a72"
_walh_surface_hex="EEE7D4"
_walh_dim_hex="BABFBA"
_walh_b03_hex="dfa000"
_walh_b15_hex="414E56"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
