#!/usr/bin/env bash
# Theme: everforest-dark
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="23/2B/31"
color01="e6/7e/80"
color02="a7/c0/80"
color03="db/bc/7f"
color04="7f/bb/b3"
color05="d6/99/b6"
color06="83/c0/92"
color07="d3/c6/aa"
color08="69/68/5F"
color09="FF/AE/AE"
color10="CC/E8/A2"
color11="FF/E1/A5"
color12="A2/E3/DA"
color13="FF/BE/DD"
color14="A6/E8/B6"
color15="ED/E0/C3"
color208="E2/9E/80"
color_background="2d/35/3b"
color_foreground="d3/c6/aa"

export WALH_THEME="everforest-dark"
export WALH_MODE="dark"
export WALH_BG="#2d353b"
export WALH_FG="#d3c6aa"
export COLORFGBG="15;0"

_walh_bg_hex="2d353b"
_walh_fg_hex="d3c6aa"
_walh_surface_hex="232B31"
_walh_dim_hex="69685F"
_walh_b03_hex="dbbc7f"
_walh_b15_hex="EDE0C3"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
