#!/usr/bin/env bash
# Theme: flexoki-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="F0/ED/E1"
color01="af/30/29"
color02="66/80/0b"
color03="ad/83/01"
color04="20/5e/a6"
color05="a0/2f/6f"
color06="24/83/7b"
color07="10/0f/0f"
color08="9A/98/92"
color09="97/00/08"
color10="51/67/00"
color11="90/6C/00"
color12="00/47/8D"
color13="89/00/59"
color14="00/6B/64"
color15="01/01/01"
color208="B0/5E/1F"
color_background="ff/fc/f0"
color_foreground="10/0f/0f"

export WALH_THEME="flexoki-light"
export WALH_MODE="light"
export WALH_BG="#fffcf0"
export WALH_FG="#100f0f"
export COLORFGBG="0;15"

_walh_bg_hex="fffcf0"
_walh_fg_hex="100f0f"
_walh_surface_hex="F0EDE1"
_walh_dim_hex="9A9892"
_walh_b03_hex="ad8301"
_walh_b15_hex="010101"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
