#!/usr/bin/env bash
# Theme: flexoki-dark
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="08/07/07"
color01="af/30/29"
color02="66/80/0b"
color03="ad/83/01"
color04="20/5e/a6"
color05="a0/2f/6f"
color06="24/83/7b"
color07="ce/cd/c3"
color08="50/4F/4B"
color09="DC/54/49"
color10="88/A5/37"
color11="D5/A8/36"
color12="41/82/D1"
color13="CC/52/93"
color14="4A/A9/A0"
color15="E8/E7/DD"
color208="B0/5E/1F"
color_background="10/0f/0f"
color_foreground="ce/cd/c3"

export WALH_THEME="flexoki-dark"
export WALH_MODE="dark"
export WALH_BG="#100f0f"
export WALH_FG="#cecdc3"
export COLORFGBG="15;0"

_walh_bg_hex="100f0f"
_walh_fg_hex="cecdc3"
_walh_surface_hex="080707"
_walh_dim_hex="504F4B"
_walh_b03_hex="ad8301"
_walh_b15_hex="E8E7DD"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
