#!/usr/bin/env bash
# Theme: github-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="F0/F0/F0"
color01="97/0b/16"
color02="07/96/2a"
color03="df/b7/1c"
color04="00/3e/8a"
color05="e9/46/91"
color06="89/d1/ec"
color07="3e/3e/3e"
color08="B0/B0/B0"
color09="73/00/0B"
color10="00/7B/1F"
color11="C3/9E/00"
color12="00/2A/63"
color13="D4/00/79"
color14="63/B9/D7"
color15="25/25/25"
color208="BF/6B/1C"
color_background="ff/ff/ff"
color_foreground="3e/3e/3e"

export WALH_THEME="github-light"
export WALH_MODE="light"
export WALH_BG="#ffffff"
export WALH_FG="#3e3e3e"
export COLORFGBG="0;15"

_walh_bg_hex="ffffff"
_walh_fg_hex="3e3e3e"
_walh_surface_hex="F0F0F0"
_walh_dim_hex="B0B0B0"
_walh_b03_hex="dfb71c"
_walh_b15_hex="252525"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
