#!/usr/bin/env bash
# Theme: github-dark
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="08/09/0D"
color01="f7/81/66"
color02="56/d3/64"
color03="e3/b3/41"
color04="6c/a4/f8"
color05="db/61/a2"
color06="2b/74/89"
color07="8b/94/9e"
color08="3A/3F/45"
color09="FF/BB/AA"
color10="79/FD/85"
color11="FF/DD/96"
color12="A9/CB/FF"
color13="FF/8D/C7"
color14="4D/99/B0"
color15="A3/AD/B7"
color208="EE/9B/57"
color_background="10/12/16"
color_foreground="8b/94/9e"

export WALH_THEME="github-dark"
export WALH_MODE="dark"
export WALH_BG="#101216"
export WALH_FG="#8b949e"
export COLORFGBG="15;0"

_walh_bg_hex="101216"
_walh_fg_hex="8b949e"
_walh_surface_hex="08090D"
_walh_dim_hex="3A3F45"
_walh_b03_hex="e3b341"
_walh_b15_hex="A3ADB7"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
