#!/usr/bin/env bash
# Theme: gruvbox-dark
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="1E/1E/1E"
color01="cc/24/1d"
color02="98/97/1a"
color03="d7/99/21"
color04="45/85/88"
color05="b1/62/86"
color06="68/9d/6a"
color07="D5/C4/A1"
color08="66/5E/4F"
color09="FC/4D/3F"
color10="BE/BD/43"
color11="FF/BF/54"
color12="66/AA/AE"
color13="DB/84/AB"
color14="8A/C4/8C"
color15="EF/DE/BA"
color208="D4/68/20"
color_background="28/28/28"
color_foreground="D5/C4/A1"

export WALH_THEME="gruvbox-dark"
export WALH_MODE="dark"
export WALH_BG="#282828"
export WALH_FG="#D5C4A1"
export COLORFGBG="15;0"

_walh_bg_hex="282828"
_walh_fg_hex="D5C4A1"
_walh_surface_hex="1E1E1E"
_walh_dim_hex="665E4F"
_walh_b03_hex="d79921"
_walh_b15_hex="EFDEBA"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
