#!/usr/bin/env bash
# Theme: gruvbox-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="EC/E2/B9"
color01="9d/00/06"
color02="79/74/0e"
color03="b5/76/14"
color04="07/66/78"
color05="8f/3f/71"
color06="42/7b/58"
color07="50/49/45"
color08="B6/AD/97"
color09="77/00/03"
color10="61/5D/00"
color11="98/60/00"
color12="00/4E/5D"
color13="7B/1E/5C"
color14="1F/65/3F"
color15="36/2F/2B"
color208="AB/4A/0D"
color_background="fb/f1/c7"
color_foreground="50/49/45"

export WALH_THEME="gruvbox-light"
export WALH_MODE="light"
export WALH_BG="#fbf1c7"
export WALH_FG="#504945"
export COLORFGBG="0;15"

_walh_bg_hex="fbf1c7"
_walh_fg_hex="504945"
_walh_surface_hex="ECE2B9"
_walh_dim_hex="B6AD97"
_walh_b03_hex="b57614"
_walh_b15_hex="362F2B"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
