#!/usr/bin/env bash
# Theme: kanagawa-wave
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="16/16/1E"
color01="c3/40/43"
color02="76/94/6a"
color03="c0/a3/6e"
color04="7e/9c/d8"
color05="95/7f/b8"
color06="6a/95/89"
color07="dc/d7/ba"
color08="60/5F/58"
color09="F1/63/63"
color10="99/BA/8C"
color11="E8/C9/90"
color12="A3/C2/FF"
color13="BB/A3/E1"
color14="8C/BB/AE"
color15="F6/F1/D4"
color208="C5/76/58"
color_background="1f/1f/28"
color_foreground="dc/d7/ba"

export WALH_THEME="kanagawa-wave"
export WALH_MODE="dark"
export WALH_BG="#1f1f28"
export WALH_FG="#dcd7ba"
export COLORFGBG="15;0"

_walh_bg_hex="1f1f28"
_walh_fg_hex="dcd7ba"
_walh_surface_hex="16161E"
_walh_dim_hex="605F58"
_walh_b03_hex="c0a36e"
_walh_b15_hex="F6F1D4"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
