#!/usr/bin/env bash
# Theme: kanagawa-lotus
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="E3/DD/AE"
color01="c8/40/53"
color02="6f/89/4e"
color03="77/71/3f"
color04="4d/69/9b"
color05="b3/5b/79"
color06="59/7b/75"
color07="54/54/64"
color08="B1/AF/A2"
color09="B5/00/37"
color10="56/72/2D"
color11="61/5A/1D"
color12="33/51/89"
color13="9F/3C/62"
color14="3E/65/5E"
color15="39/39/48"
color208="A3/5F/49"
color_background="f2/ec/bc"
color_foreground="54/54/64"

export WALH_THEME="kanagawa-lotus"
export WALH_MODE="light"
export WALH_BG="#f2ecbc"
export WALH_FG="#545464"
export COLORFGBG="0;15"

_walh_bg_hex="f2ecbc"
_walh_fg_hex="545464"
_walh_surface_hex="E3DDAE"
_walh_dim_hex="B1AFA2"
_walh_b03_hex="77713f"
_walh_b15_hex="393948"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
