#!/usr/bin/env bash
# Theme: light-owl
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="EC/EC/EC"
color01="de/3d/3b"
color02="08/91/6a"
color03="da/aa/01"
color04="28/8e/d7"
color05="d6/43/8a"
color06="2a/a2/98"
color07="40/3f/53"
color08="AF/AE/BA"
color09="C6/00/1A"
color10="00/76/56"
color11="BC/92/00"
color12="00/75/BA"
color13="C2/00/73"
color14="00/89/80"
color15="27/26/38"
color208="DF/7A/2E"
color_background="fb/fb/fb"
color_foreground="40/3f/53"

export WALH_THEME="light-owl"
export WALH_MODE="light"
export WALH_BG="#fbfbfb"
export WALH_FG="#403f53"
export COLORFGBG="0;15"

_walh_bg_hex="fbfbfb"
_walh_fg_hex="403f53"
_walh_surface_hex="ECECEC"
_walh_dim_hex="AFAEBA"
_walh_b03_hex="daaa01"
_walh_b15_hex="272638"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
