#!/usr/bin/env bash
# Theme: material-dark
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="1C/28/2E"
color01="f0/71/78"
color02="c3/e8/8d"
color03="ff/cb/6b"
color04="82/aa/ff"
color05="c7/92/ea"
color06="89/dd/ff"
color07="ee/ff/ff"
color08="6B/79/7D"
color09="FF/AA/AB"
color10="CE/F5/94"
color11="FF/E0/AB"
color12="BD/D3/FF"
color13="E6/C1/FF"
color14="C1/EC/FF"
color15="F1/FF/FF"
color208="F9/A0/74"
color_background="26/32/38"
color_foreground="ee/ff/ff"

export WALH_THEME="material-dark"
export WALH_MODE="dark"
export WALH_BG="#263238"
export WALH_FG="#eeffff"
export COLORFGBG="15;0"

_walh_bg_hex="263238"
_walh_fg_hex="eeffff"
_walh_surface_hex="1C282E"
_walh_dim_hex="6B797D"
_walh_b03_hex="ffcb6b"
_walh_b15_hex="F1FFFF"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
