#!/usr/bin/env bash
# Theme: material-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="EB/EB/EB"
color01="e5/39/35"
color02="91/b8/59"
color03="f6/a4/34"
color04="61/82/b8"
color05="7c/4d/ff"
color06="39/ad/b5"
color07="54/6e/7a"
color08="B5/C3/CA"
color09="CA/00/15"
color10="75/A0/2B"
color11="DB/8B/00"
color12="45/6A/A6"
color13="6A/03/F5"
color14="00/94/9D"
color15="39/52/5D"
color208="F0/74/36"
color_background="fa/fa/fa"
color_foreground="54/6e/7a"

export WALH_THEME="material-light"
export WALH_MODE="light"
export WALH_BG="#fafafa"
export WALH_FG="#546e7a"
export COLORFGBG="0;15"

_walh_bg_hex="fafafa"
_walh_fg_hex="546e7a"
_walh_surface_hex="EBEBEB"
_walh_dim_hex="B5C3CA"
_walh_b03_hex="f6a434"
_walh_b15_hex="39525D"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
