#!/usr/bin/env bash
# Theme: monokai-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="EA/E9/E6"
color01="ff/61/88"
color02="a9/dc/76"
color03="ff/d8/66"
color04="78/dc/e8"
color05="ab/9d/f2"
color06="78/dc/e8"
color07="40/3e/41"
color08="AE/AC/AD"
color09="ED/31/6D"
color10="8B/C4/4B"
color11="E9/BD/22"
color12="47/C4/D2"
color13="93/81/E1"
color14="47/C4/D2"
color15="27/25/28"
color208="FF/A3/80"
color_background="f9/f8/f5"
color_foreground="40/3e/41"

export WALH_THEME="monokai-light"
export WALH_MODE="light"
export WALH_BG="#f9f8f5"
export WALH_FG="#403e41"
export COLORFGBG="0;15"

_walh_bg_hex="f9f8f5"
_walh_fg_hex="403e41"
_walh_surface_hex="EAE9E6"
_walh_dim_hex="AEACAD"
_walh_b03_hex="ffd866"
_walh_b15_hex="272528"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
