#!/usr/bin/env bash
# Theme: monokai-pro
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="23/20/24"
color01="ff/61/88"
color02="a9/dc/76"
color03="ff/d8/66"
color04="78/dc/e8"
color05="ab/9d/f2"
color06="78/dc/e8"
color07="fc/fc/fa"
color08="74/73/74"
color09="FF/AB/B9"
color10="C2/F9/8C"
color11="FF/E2/92"
color12="A2/F5/FF"
color13="D0/CA/FF"
color14="A2/F5/FF"
color15="FC/FC/FA"
color208="FF/A3/80"
color_background="2d/2a/2e"
color_foreground="fc/fc/fa"

export WALH_THEME="monokai-pro"
export WALH_MODE="dark"
export WALH_BG="#2d2a2e"
export WALH_FG="#fcfcfa"
export COLORFGBG="15;0"

_walh_bg_hex="2d2a2e"
_walh_fg_hex="fcfcfa"
_walh_surface_hex="232024"
_walh_dim_hex="747374"
_walh_b03_hex="ffd866"
_walh_b15_hex="FCFCFA"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
