#!/usr/bin/env bash
# Theme: night-owl
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="00/0D/1B"
color01="f7/8c/6c"
color02="ad/db/67"
color03="ff/cb/8b"
color04="82/aa/ff"
color05="c7/92/ea"
color06="7f/db/ca"
color07="be/c5/d4"
color08="43/52/62"
color09="FF/C4/B2"
color10="C7/F8/7D"
color11="FF/DF/B8"
color12="BD/D3/FF"
color13="E6/C1/FF"
color14="98/FA/E8"
color15="D8/DF/EE"
color208="FC/AC/7B"
color_background="01/16/27"
color_foreground="be/c5/d4"

export WALH_THEME="night-owl"
export WALH_MODE="dark"
export WALH_BG="#011627"
export WALH_FG="#bec5d4"
export COLORFGBG="15;0"

_walh_bg_hex="011627"
_walh_fg_hex="bec5d4"
_walh_surface_hex="000D1B"
_walh_dim_hex="435262"
_walh_b03_hex="ffcb8b"
_walh_b15_hex="D8DFEE"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
