#!/usr/bin/env bash
# Theme: nightfox
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="10/1A/26"
color01="c9/4f/6d"
color02="81/b2/9a"
color03="db/c0/74"
color04="71/9c/d6"
color05="9d/79/d6"
color06="63/cd/cf"
color07="cd/ce/cf"
color08="58/5E/66"
color09="F6/71/90"
color10="A4/D9/BF"
color11="FF/E2/92"
color12="95/C2/FF"
color13="C2/9E/FF"
color14="86/F6/F8"
color15="E7/E8/E9"
color208="D5/8A/72"
color_background="19/23/30"
color_foreground="cd/ce/cf"

export WALH_THEME="nightfox"
export WALH_MODE="dark"
export WALH_BG="#192330"
export WALH_FG="#cdcecf"
export COLORFGBG="15;0"

_walh_bg_hex="192330"
_walh_fg_hex="cdcecf"
_walh_surface_hex="101A26"
_walh_dim_hex="585E66"
_walh_b03_hex="dbc074"
_walh_b15_hex="E7E8E9"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
