#!/usr/bin/env bash
# Theme: nord-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="DD/E0/E5"
color01="bf/61/6a"
color02="a3/be/8c"
color03="eb/cb/8b"
color04="5e/81/ac"
color05="b4/8e/ad"
color06="88/c0/d0"
color07="2e/34/40"
color08="9D/A3/AC"
color09="AC/42/50"
color10="88/A6/6D"
color11="D5/B0/66"
color12="42/69/99"
color13="9E/74/97"
color14="67/A8/BA"
color15="16/1C/26"
color208="D7/96/7B"
color_background="ec/ef/f4"
color_foreground="2e/34/40"

export WALH_THEME="nord-light"
export WALH_MODE="light"
export WALH_BG="#eceff4"
export WALH_FG="#2e3440"
export COLORFGBG="0;15"

_walh_bg_hex="eceff4"
_walh_fg_hex="2e3440"
_walh_surface_hex="DDE0E5"
_walh_dim_hex="9DA3AC"
_walh_b03_hex="ebcb8b"
_walh_b15_hex="161C26"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
