#!/usr/bin/env bash
# Theme: nord
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="24/2A/36"
color01="bf/61/6a"
color02="a3/be/8c"
color03="eb/cb/8b"
color04="81/a1/c1"
color05="b4/8e/ad"
color06="88/c0/d0"
color07="d8/de/e9"
color08="6A/70/7B"
color09="EB/83/8C"
color10="C8/E6/AF"
color11="FF/E1/A5"
color12="A4/C7/EA"
color13="DC/B2/D4"
color14="AB/E8/F9"
color15="F5/F8/FF"
color208="D7/96/7B"
color_background="2e/34/40"
color_foreground="d8/de/e9"

export WALH_THEME="nord"
export WALH_MODE="dark"
export WALH_BG="#2e3440"
export WALH_FG="#d8dee9"
export COLORFGBG="15;0"

_walh_bg_hex="2e3440"
_walh_fg_hex="d8dee9"
_walh_surface_hex="242A36"
_walh_dim_hex="6A707B"
_walh_b03_hex="ebcb8b"
_walh_b15_hex="F5F8FF"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
