#!/usr/bin/env bash
# Theme: oceanic-next
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# Normal
color00="33/42/4B" # Black
color01="e5/4b/4b" # Red
color02="89/d2/87" # Green
color03="e5/c7/6b" # Yellow
color04="6c/99/bb" # Blue
color05="b7/7e/b8" # Magenta
color06="51/a8/b3" # Cyan
color07="C6/CA/D2" # Grey

# Bright
color08="7D/87/90" # Dark Grey
color09="e5/4b/4b" # Red
color10="89/d2/87" # Green
color11="e5/c7/6b" # Yellow
color12="6c/99/bb" # Blue
color13="b7/7e/b8" # Magenta
color14="51/a8/b3" # Cyan
color15="F2/F3/F5" # White

# 256 color
color208="E5/89/5B" # Orange

# Base
color_background="1b/2b/34" # Black
color_foreground="c0/c5/ce" # Grey

# Announce the active palette to programs launched from this shell
export WALH_THEME="oceanic-next"
export WALH_MODE="dark"
export WALH_BG="#1b2b34"
export WALH_FG="#c0c5ce"
# ncurses/rxvt convention: programs like mutt and rho read this to adopt
# the palette's mode without querying the terminal
export COLORFGBG="15;0"
if [ "${WALH_SYNC_FZF:-}" = "1" ]; then
  export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }--color=bg:#1b2b34,bg+:#e54b4b,fg:#c0c5ce,fg+:#51a8b3,hl:#6c99bb,hl+:#6c99bb,info:#89d287,prompt:#89d287,pointer:#51a8b3,marker:#51a8b3,spinner:#51a8b3,header:#6c99bb"
fi
if [ -z "$WALH_RESTORE" ]; then
  state_dir="${XDG_CACHE_HOME:-$HOME/.cache}/walh"
  mkdir -p "$state_dir"
  cat > "$state_dir/state.toml" <<STATEEOF
theme = "oceanic-next"
mode = "dark"
background = "#1b2b34"
foreground = "#c0c5ce"
surface = "#33424B"
dim = "#7D8790"
STATEEOF
fi

walh_buffer=""
if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ]; then
  walh_append() {
    local _c
    # shellcheck disable=SC2059
    printf -v _c "$@"
    walh_buffer="${walh_buffer}${_c}"
  }
else
  walh_append() {
    # shellcheck disable=SC2059
    walh_buffer="${walh_buffer}$(printf "$@")"
  }
fi

# shellcheck disable=SC1003
if [ -n "$TMUX" ]; then
  # Tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  put_template() { walh_append '\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\' "$@"; }
  put_template_var() { walh_append '\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\' "$@"; }
  put_template_custom() { walh_append '\033Ptmux;\033\033]%s%s\033\033\\\033\\' "$@"; }
elif [ "${TERM%%[-.]*}" = "screen" ]; then
  # GNU screen (screen, screen-256color, screen-256color-bce)
  put_template() { walh_append '\033P\033]4;%d;rgb:%s\007\033\\' "$@"; }
  put_template_var() { walh_append '\033P\033]%d;rgb:%s\007\033\\' "$@"; }
  put_template_custom() { walh_append '\033P\033]%s%s\007\033\\' "$@"; }
elif [ "${TERM%%-*}" = "linux" ]; then
  put_template() { [ "$1" -lt 16 ] && walh_append '\033]P%x%s' "$1" "$(echo "$2" | sed 's/\///g')"; }
  put_template_var() { true; }
  put_template_custom() { true; }
else
  put_template() { walh_append '\033]4;%d;rgb:%s\033\\' "$@"; }
  put_template_var() { walh_append '\033]%d;rgb:%s\033\\' "$@"; }
  put_template_custom() { walh_append '\033]%s%s\033\\' "$@"; }
fi

# 16 color space
put_template 0 "$color00"
put_template 1 "$color01"
put_template 2 "$color02"
put_template 3 "$color03"
put_template 4 "$color04"
put_template 5 "$color05"
put_template 6 "$color06"
put_template 7 "$color07"
put_template 8 "$color08"
put_template 9 "$color09"
put_template 10 "$color10"
put_template 11 "$color11"
put_template 12 "$color12"
put_template 13 "$color13"
put_template 14 "$color14"
put_template 15 "$color15"

# 256 color space
put_template 208 "$color208"

# foreground / background / cursor color
if [ -n "$ITERM_SESSION_ID" ]; then
  # iTerm2 proprietary escape codes
  put_template_custom Pg c0c5ce # foreground
  put_template_custom Ph 1b2b34 # background
  put_template_custom Pi F2F3F5 # bold color
  put_template_custom Pj e5c76b # selection color
  put_template_custom Pk 1b2b34 # selected text color
  put_template_custom Pl c0c5ce # cursor
  put_template_custom Pm 1b2b34 # cursor text
else
  put_template_var 10 "$color_foreground"
  if [ "$WALH_SHELL_SET_BACKGROUND" != false ]; then
    put_template_var 11 "$color_background"
    if [ "${TERM%%-*}" = "rxvt" ]; then
      put_template_var 708 "$color_background" # internal border (rxvt)
    fi
  fi
  put_template_custom 12 ";7" # cursor (reverse video)
fi

[ -n "$walh_buffer" ] && printf '%s' "$walh_buffer"

# clean up
for fn in walh_append put_template put_template_var put_template_custom; do
  unset -f "$fn" 2>/dev/null || true
done
for var in \
  walh_buffer \
  color00 color01 color02 color03 color04 color05 color06 color07 \
  color08 color09 color10 color11 color12 color13 color14 color15 \
  color208 color_foreground color_background state_dir; do
  unset "$var" 2>/dev/null || true
done
