#!/usr/bin/env bash
# Theme: onedark
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="1E/22/2A"
color01="e0/6c/75"
color02="98/c3/79"
color03="e5/c0/7b"
color04="61/af/ef"
color05="c6/78/dd"
color06="56/b6/c2"
color07="ab/b2/bf"
color08="56/5B/65"
color09="FF/9A/9F"
color10="BC/EB/9B"
color11="FF/E0/A8"
color12="A3/D4/FF"
color13="EA/A2/FF"
color14="79/DE/EB"
color15="C4/CB/D9"
color208="E5/97/79"
color_background="28/2c/34"
color_foreground="ab/b2/bf"

export WALH_THEME="onedark"
export WALH_MODE="dark"
export WALH_BG="#282c34"
export WALH_FG="#abb2bf"
export COLORFGBG="15;0"

_walh_bg_hex="282c34"
_walh_fg_hex="abb2bf"
_walh_surface_hex="1E222A"
_walh_dim_hex="565B65"
_walh_b03_hex="e5c07b"
_walh_b15_hex="C4CBD9"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
