#!/usr/bin/env bash
# Theme: onelight
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="EB/EB/EB"
color01="ca/12/43"
color02="50/a1/4f"
color03="c1/84/01"
color04="40/78/f2"
color05="a6/26/a4"
color06="01/84/bc"
color07="38/3a/42"
color08="AA/AC/B0"
color09="A5/00/33"
color10="25/8B/29"
color11="A2/6E/00"
color12="1D/59/E6"
color13="8A/00/89"
color14="00/6B/9A"
color15="1F/21/28"
color208="C8/5A/33"
color_background="fa/fa/fa"
color_foreground="38/3a/42"

export WALH_THEME="onelight"
export WALH_MODE="light"
export WALH_BG="#fafafa"
export WALH_FG="#383a42"
export COLORFGBG="0;15"

_walh_bg_hex="fafafa"
_walh_fg_hex="383a42"
_walh_surface_hex="EBEBEB"
_walh_dim_hex="AAACB0"
_walh_b03_hex="c18401"
_walh_b15_hex="1F2128"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
