#!/usr/bin/env bash
# Theme: papercolor-dark
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="13/13/13"
color01="af/00/5f"
color02="5f/af/00"
color03="d7/af/5f"
color04="5f/af/d7"
color05="80/80/80"
color06="d7/87/5f"
color07="d0/d0/d0"
color08="5A/5A/5A"
color09="DD/37/82"
color10="81/D7/39"
color11="FF/D6/85"
color12="86/D6/FF"
color13="A4/A4/A4"
color14="FF/AD/85"
color15="EA/EA/EA"
color208="C7/6B/64"
color_background="1c/1c/1c"
color_foreground="d0/d0/d0"

export WALH_THEME="papercolor-dark"
export WALH_MODE="dark"
export WALH_BG="#1c1c1c"
export WALH_FG="#d0d0d0"
export COLORFGBG="15;0"

_walh_bg_hex="1c1c1c"
_walh_fg_hex="d0d0d0"
_walh_surface_hex="131313"
_walh_dim_hex="5A5A5A"
_walh_b03_hex="d7af5f"
_walh_b15_hex="EAEAEA"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
