#!/usr/bin/env bash
# Theme: papercolor-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="DF/DF/DF"
color01="af/00/00"
color02="00/87/00"
color03="5f/87/00"
color04="00/87/af"
color05="87/87/af"
color06="00/5f/87"
color07="44/44/44"
color08="A9/A9/A9"
color09="88/00/00"
color10="00/6C/00"
color11="4C/6D/00"
color12="00/6E/8F"
color13="6F/6E/9B"
color14="00/48/67"
color15="2A/2A/2A"
color208="93/5C/00"
color_background="ee/ee/ee"
color_foreground="44/44/44"

export WALH_THEME="papercolor-light"
export WALH_MODE="light"
export WALH_BG="#eeeeee"
export WALH_FG="#444444"
export COLORFGBG="0;15"

_walh_bg_hex="eeeeee"
_walh_fg_hex="444444"
_walh_surface_hex="DFDFDF"
_walh_dim_hex="A9A9A9"
_walh_b03_hex="5f8700"
_walh_b15_hex="2A2A2A"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
