#!/usr/bin/env bash
# Theme: rose-pine-dawn
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="EB/E5/DE"
color01="b4/63/7a"
color02="28/69/83"
color03="ea/9d/34"
color04="56/94/9f"
color05="90/7a/a9"
color06="d7/82/7e"
color07="57/52/79"
color08="B7/B3/C6"
color09="A0/46/62"
color10="00/52/6D"
color11="CF/84/00"
color12="31/7D/8A"
color13="7A/61/95"
color14="C3/65/62"
color15="3C/37/5C"
color208="CE/81/62"
color_background="fa/f4/ed"
color_foreground="57/52/79"

export WALH_THEME="rose-pine-dawn"
export WALH_MODE="light"
export WALH_BG="#faf4ed"
export WALH_FG="#575279"
export COLORFGBG="0;15"

_walh_bg_hex="faf4ed"
_walh_fg_hex="575279"
_walh_surface_hex="EBE5DE"
_walh_dim_hex="B7B3C6"
_walh_b03_hex="ea9d34"
_walh_b15_hex="3C375C"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
