#!/usr/bin/env bash
# Theme: rose-pine
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="10/0E/1A"
color01="eb/6f/92"
color02="31/74/8f"
color03="f6/c1/77"
color04="9c/cf/d8"
color05="c4/a7/e7"
color06="eb/bc/ba"
color07="e0/de/f4"
color08="5C/5B/6C"
color09="FF/A6/BB"
color10="53/99/B6"
color11="FF/DF/B5"
color12="B9/F0/F9"
color13="E6/D3/FF"
color14="FF/DB/D9"
color15="FB/FB/FF"
color208="F2/9A/88"
color_background="19/17/24"
color_foreground="e0/de/f4"

export WALH_THEME="rose-pine"
export WALH_MODE="dark"
export WALH_BG="#191724"
export WALH_FG="#e0def4"
export COLORFGBG="15;0"

_walh_bg_hex="191724"
_walh_fg_hex="e0def4"
_walh_surface_hex="100E1A"
_walh_dim_hex="5C5B6C"
_walh_b03_hex="f6c177"
_walh_b15_hex="FBFBFF"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
