#!/usr/bin/env bash
# Theme: solarized-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="EE/E7/D4"
color01="dc/32/2f"
color02="85/99/00"
color03="b5/89/00"
color04="26/8b/d2"
color05="6c/71/c4"
color06="2a/a1/98"
color07="58/6e/75"
color08="B8/C1/BC"
color09="BF/00/12"
color10="6F/80/00"
color11="98/72/00"
color12="00/72/B5"
color13="55/56/B4"
color14="00/88/80"
color15="3D/52/59"
color208="CB/66/22"
color_background="fd/f6/e3"
color_foreground="58/6e/75"

export WALH_THEME="solarized-light"
export WALH_MODE="light"
export WALH_BG="#fdf6e3"
export WALH_FG="#586e75"
export COLORFGBG="0;15"

_walh_bg_hex="fdf6e3"
_walh_fg_hex="586e75"
_walh_surface_hex="EEE7D4"
_walh_dim_hex="B8C1BC"
_walh_b03_hex="b58900"
_walh_b15_hex="3D5259"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
