#!/usr/bin/env bash
# Theme: solarized-dark
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="00/21/2A"
color01="dc/32/2f"
color02="85/99/00"
color03="b5/89/00"
color04="26/8b/d2"
color05="6c/71/c4"
color06="2a/a1/98"
color07="93/a1/a1"
color08="3C/55/5B"
color09="FF/69/5D"
color10="A9/C0/37"
color11="DE/AE/37"
color12="4C/B1/FF"
color13="8E/95/F0"
color14="51/C8/BE"
color15="AC/BA/BA"
color208="CB/66/22"
color_background="00/2b/36"
color_foreground="93/a1/a1"

export WALH_THEME="solarized-dark"
export WALH_MODE="dark"
export WALH_BG="#002b36"
export WALH_FG="#93a1a1"
export COLORFGBG="15;0"

_walh_bg_hex="002b36"
_walh_fg_hex="93a1a1"
_walh_surface_hex="00212A"
_walh_dim_hex="3C555B"
_walh_b03_hex="b58900"
_walh_b15_hex="ACBABA"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
