#!/usr/bin/env bash
# Theme: tokyo-night-day
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="D2/D3/D8"
color01="f5/2a/65"
color02="58/75/39"
color03="8c/6c/3e"
color04="2e/7d/e9"
color05="98/54/f1"
color06="00/71/97"
color07="37/60/bf"
color08="98/B1/E6"
color09="D3/00/50"
color10="3F/5F/15"
color11="77/54/1A"
color12="00/63/D2"
color13="85/23/E5"
color14="00/59/78"
color15="1D/42/9E"
color208="C2/59/52"
color_background="e1/e2/e7"
color_foreground="37/60/bf"

export WALH_THEME="tokyo-night-day"
export WALH_MODE="light"
export WALH_BG="#e1e2e7"
export WALH_FG="#3760bf"
export COLORFGBG="0;15"

_walh_bg_hex="e1e2e7"
_walh_fg_hex="3760bf"
_walh_surface_hex="D2D3D8"
_walh_dim_hex="98B1E6"
_walh_b03_hex="8c6c3e"
_walh_b15_hex="1D429E"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
