#!/usr/bin/env bash
# Theme: tokyo-night
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="11/12/1C"
color01="f7/76/8e"
color02="9e/ce/6a"
color03="e0/af/68"
color04="7a/a2/f7"
color05="ad/8e/e6"
color06="44/9d/ab"
color07="a9/b1/d6"
color08="4B/4F/65"
color09="FF/B4/BE"
color10="C2/F7/8B"
color11="FF/D8/A3"
color12="B0/CA/FF"
color13="D0/B9/FF"
color14="67/C4/D3"
color15="C2/CB/F0"
color208="ED/95/7D"
color_background="1a/1b/26"
color_foreground="a9/b1/d6"

export WALH_THEME="tokyo-night"
export WALH_MODE="dark"
export WALH_BG="#1a1b26"
export WALH_FG="#a9b1d6"
export COLORFGBG="15;0"

_walh_bg_hex="1a1b26"
_walh_fg_hex="a9b1d6"
_walh_surface_hex="11121C"
_walh_dim_hex="4B4F65"
_walh_b03_hex="e0af68"
_walh_b15_hex="C2CBF0"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
