#!/usr/bin/env bash
# Theme: tomorrow
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# Normal
color00="E5/E5/E5" # Black
color01="C8/28/29" # Red
color02="71/8C/00" # Green
color03="EA/B7/00" # Yellow
color04="42/71/AE" # Blue
color05="89/59/A8" # Magenta
color06="3E/99/9F" # Cyan
color07="5E/5E/5D" # Grey

# Bright
color08="A6/A6/A5" # Dark Grey
color09="C8/28/29" # Red
color10="71/8C/00" # Green
color11="EA/B7/00" # Yellow
color12="42/71/AE" # Blue
color13="89/59/A8" # Magenta
color14="3E/99/9F" # Cyan
color15="3D/3D/3C" # White

# 256 color
color208="D9/6F/14" # Orange

# Base
color_background="FF/FF/FF" # Black
color_foreground="4D/4D/4C" # Grey

if [ -n "$TMUX" ]; then
  # Tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  put_template() { printf '\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\' "$@"; }
  put_template_var() { printf '\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\' "$@"; }
  put_template_custom() { printf '\033Ptmux;\033\033]%s%s\033\033\\\033\\' "$@"; }
elif [ "${TERM%%[-.]*}" = "screen" ]; then
  # GNU screen (screen, screen-256color, screen-256color-bce)
  put_template() { printf '\033P\033]4;%d;rgb:%s\007\033\\' "$@"; }
  put_template_var() { printf '\033P\033]%d;rgb:%s\007\033\\' "$@"; }
  put_template_custom() { printf '\033P\033]%s%s\007\033\\' "$@"; }
elif [ "${TERM%%-*}" = "linux" ]; then
  put_template() { [ "$1" -lt 16 ] && printf "\e]P%x%s" "$1" "$(echo "$2" | sed 's/\///g')"; }
  put_template_var() { true; }
  put_template_custom() { true; }
else
  put_template() { printf '\033]4;%d;rgb:%s\033\\' "$@"; }
  put_template_var() { printf '\033]%d;rgb:%s\033\\' "$@"; }
  put_template_custom() { printf '\033]%s%s\033\\' "$@"; }
fi

# 16 color space
put_template 0 "$color00"
put_template 1 "$color01"
put_template 2 "$color02"
put_template 3 "$color03"
put_template 4 "$color04"
put_template 5 "$color05"
put_template 6 "$color06"
put_template 7 "$color07"
put_template 8 "$color08"
put_template 9 "$color09"
put_template 10 "$color10"
put_template 11 "$color11"
put_template 12 "$color12"
put_template 13 "$color13"
put_template 14 "$color14"
put_template 15 "$color15"

# 256 color space
put_template 208 "$color208"

# foreground / background / cursor color
if [ -n "$ITERM_SESSION_ID" ]; then
  # iTerm2 proprietary escape codes
  put_template_custom Pg 4D4D4C # foreground
  put_template_custom Ph FFFFFF # background
  put_template_custom Pi 3D3D3C # bold color
  put_template_custom Pj EAB700 # selection color
  put_template_custom Pk FFFFFF # selected text color
  put_template_custom Pl 4D4D4C # cursor
  put_template_custom Pm FFFFFF # cursor text
else
  put_template_var 10 "$color_foreground"
  if [ "$WALH_SHELL_SET_BACKGROUND" != false ]; then
    put_template_var 11 "$color_background"
    if [ "${TERM%%-*}" = "rxvt" ]; then
      put_template_var 708 "$color_background" # internal border (rxvt)
    fi
  fi
  put_template_custom 12 ";7" # cursor (reverse video)
fi

# clean up
for fn in put_template put_template_var put_template_custom; do
  unset -f "$fn" 2>/dev/null || true
done
for var in \
  color00 color01 color02 color03 color04 color05 color06 color07 \
  color08 color09 color10 color11 color12 color13 color14 color15 \
  color208 color_foreground color_background; do
  unset "$var" 2>/dev/null || true
done
