#!/usr/bin/env bash
# Theme: tomorrow-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="F0/F0/F0"
color01="c8/28/29"
color02="71/8c/00"
color03="ea/b7/00"
color04="42/71/ae"
color05="89/59/a8"
color06="3e/99/9f"
color07="4d/4d/4c"
color08="B7/B7/B7"
color09="A9/00/12"
color10="5C/73/00"
color11="CC/9F/00"
color12="21/59/9D"
color13="75/3C/96"
color14="00/82/89"
color15="33/33/32"
color208="DD/77/23"
color_background="ff/ff/ff"
color_foreground="4d/4d/4c"

export WALH_THEME="tomorrow-light"
export WALH_MODE="light"
export WALH_BG="#ffffff"
export WALH_FG="#4d4d4c"
export COLORFGBG="0;15"

_walh_bg_hex="ffffff"
_walh_fg_hex="4d4d4c"
_walh_surface_hex="F0F0F0"
_walh_dim_hex="B7B7B7"
_walh_b03_hex="eab700"
_walh_b15_hex="333332"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
