#!/usr/bin/env bash
# Theme: tomorrow-dark
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="14/16/18"
color01="cc/66/66"
color02="b5/bd/68"
color03="f0/c6/74"
color04="81/a2/be"
color05="b2/94/bb"
color06="8a/be/b7"
color07="c5/c8/c6"
color08="57/59/5A"
color09="F9/89/88"
color10="DB/E4/89"
color11="FF/E0/A7"
color12="A4/C8/E7"
color13="D9/B9/E3"
color14="AE/E6/DE"
color15="DF/E2/E0"
color208="DF/97/6E"
color_background="1d/1f/21"
color_foreground="c5/c8/c6"

export WALH_THEME="tomorrow-dark"
export WALH_MODE="dark"
export WALH_BG="#1d1f21"
export WALH_FG="#c5c8c6"
export COLORFGBG="15;0"

_walh_bg_hex="1d1f21"
_walh_fg_hex="c5c8c6"
_walh_surface_hex="141618"
_walh_dim_hex="57595A"
_walh_b03_hex="f0c674"
_walh_b15_hex="DFE2E0"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
