#!/usr/bin/env bash
# Theme: vscode-light
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="F0/F0/F0"
color01="cd/31/31"
color02="00/80/00"
color03="79/5e/26"
color04="04/51/a5"
color05="bc/3f/bc"
color06="09/86/58"
color07="1e/1e/1e"
color08="A1/A1/A1"
color09="B1/00/16"
color10="00/65/00"
color11="63/47/00"
color12="00/3C/7F"
color13="A7/00/A8"
color14="00/6C/45"
color15="08/08/08"
color208="A5/4F/2C"
color_background="ff/ff/ff"
color_foreground="1e/1e/1e"

export WALH_THEME="vscode-light"
export WALH_MODE="light"
export WALH_BG="#ffffff"
export WALH_FG="#1e1e1e"
export COLORFGBG="0;15"

_walh_bg_hex="ffffff"
_walh_fg_hex="1e1e1e"
_walh_surface_hex="F0F0F0"
_walh_dim_hex="A1A1A1"
_walh_b03_hex="795e26"
_walh_b15_hex="080808"

if [ -n "${WALH_SHELL:-}" ] && [ -f "${WALH_SHELL}/engine.sh" ]; then
  _walh_engine="${WALH_SHELL}/engine.sh"
elif [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  eval '_walh_engine="${${(%):-%x}:A:h:h}/engine.sh"'
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
  _walh_dir=""
  _walh_i=0
  while [ -L "$_walh_src" ] && [ "$_walh_i" -lt 10 ]; do
    _walh_i=$((_walh_i + 1))
    _walh_dir="$(cd -P "$(dirname "$_walh_src")" 2>/dev/null && pwd)"
    _walh_src="$(readlink "$_walh_src" 2>/dev/null)" || break
    case "$_walh_src" in
      /*) ;;
      *) _walh_src="$_walh_dir/$_walh_src" ;;
    esac
  done
  [ -z "$_walh_dir" ] && _walh_dir="$(cd -P "$(dirname "$_walh_src")/.." 2>/dev/null && pwd)"
  _walh_engine="${_walh_dir}/engine.sh"
fi

if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
