#!/usr/bin/env bash
# Theme: vscode
#
# This file is auto-generated by generate_themes.py. Do not edit directly.
# Usage: source this script in your shell to apply the theme.

# shellcheck disable=SC2034
color00="15/15/15"
color01="cd/31/31"
color02="0d/bc/79"
color03="e5/e5/10"
color04="24/72/c8"
color05="bc/3f/bc"
color06="11/a8/cd"
color07="cc/cc/cc"
color08="5A/5A/5A"
color09="FC/57/51"
color10="45/E5/9C"
color11="EF/EE/00"
color12="47/97/F5"
color13="E8/63/E7"
color14="44/CF/F8"
color15="E6/E6/E6"
color208="E1/93/2E"
color_background="1e/1e/1e"
color_foreground="cc/cc/cc"

export WALH_THEME="vscode"
export WALH_MODE="dark"
export WALH_BG="#1e1e1e"
export WALH_FG="#cccccc"
export COLORFGBG="15;0"

_walh_bg_hex="1e1e1e"
_walh_fg_hex="cccccc"
_walh_surface_hex="151515"
_walh_dim_hex="5A5A5A"
_walh_b03_hex="e5e510"
_walh_b15_hex="E6E6E6"

if [ -n "${ZSH_VERSION:-}" ]; then
  # shellcheck disable=SC2296
  _walh_src="${(%):-%x}"
else
  _walh_src="${BASH_SOURCE[0]:-$0}"
fi
while [ -L "$_walh_src" ]; do
  _walh_dir="$(cd "$(dirname "$_walh_src")" && pwd)"
  _walh_src="$(readlink "$_walh_src")"
  [ "${_walh_src#/}" = "$_walh_src" ] && _walh_src="$_walh_dir/$_walh_src"
done
_walh_dir="$(cd "$(dirname "$_walh_src")/.." && pwd)"
if [ -f "$_walh_dir/engine.sh" ]; then
  _walh_engine="$_walh_dir/engine.sh"
elif [ -n "${WALH_SHELL:-}" ] && [ -f "$WALH_SHELL/engine.sh" ]; then
  _walh_engine="$WALH_SHELL/engine.sh"
fi
if [ -n "${_walh_engine:-}" ] && [ -f "$_walh_engine" ]; then
  # shellcheck disable=SC1090
  . "$_walh_engine"
fi
